# Generated by Django 4.2.7 on 2024-01-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='account_no',
        ),
    ]
