# Generated by Django 4.2.7 on 2024-01-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotelinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
