# Generated by Django 4.2.7 on 2024-01-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotelinfo_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='hotel_image',
            field=models.ImageField(null=True, upload_to='hotel/media/uploads/'),
        ),
    ]
