# Generated by Django 4.2.7 on 2024-01-16 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookHotelModel',
        ),
    ]
